apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
stringData:
  DB_HOST: mysql          # ClusterIP service name
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: root
  DB_NAME: home           # use DB_NAME instead of MYSQL_DATABASE
  SECRET_KEY: eade83f40d0ad2d78a155fcdd338385ba1
