apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: mysql-kube
        image: mugilaaru/mugil_private:1.2
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: flask-secrets
