pipeline {
    agent any
    environment {
        IMAGE_NAME = "flask_app"
        VERSION = "${env.BUILD_NUMBER}"   // Jenkins build number as version
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'upload_functions', url: 'https://github.com/mugilanaaru/python_script.git'
            }
        }
        stage('Build') {
            steps {
                sh "docker compose -f project/docker-compose.yml build"
                sh "docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${VERSION}"
            }
        }
        stage('Archive Artifacts') {
            steps {
                // Save version info as artifact
                sh "echo Build version: ${VERSION} > build-info.txt"
                archiveArtifacts artifacts: 'build-info.txt', fingerprint: true
            }
        }
        stage('Deploy') {
            steps {
                sh "docker compose -f project/docker-compose.yml up -d"
            }
        }
    }
}