apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: flask-app-ns
spec:
  serviceName: mysql   # must match ClusterIP service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: mysql-kube
        image: mugilaaru/mugil_private:1.2
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: flask-secrets
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
